### ISSUE TITLE
Baudrate does not match

### ISSUE THREAD

**Issue by dragosmacovei** [ECC-BFMC/Embedded_Platform#1]
In **file** `SerialHandler.py` in **class** `SerialHandler` in the **constructor** you set the baudrate to 460800.
```
    def __init__(self,f_device_File='/dev/ttyACM0',f_history_file='historyFile.txt'):
        self.serialCon=serial.Serial(f_device_File,460800,timeout=1)
        self.historyFile=FileHandler(f_history_file)
        self.readThread=ReadThread(1,self.serialCon,self.historyFile)
        self.lock=threading.Lock()
```

Under the `Embedded Platform` folder inside the main.cpp **file** at _line 41_ you crate the `Serial `object _with the default baudrate (9600)_:
`Serial          g_rpi(USBTX, USBRX);`

then in the setup you change it to 256000:
```
uint32_t setup()
{
    g_rpi.baud(256000);  
    g_rpi.printf("\r\n\r\n");
    g_rpi.printf("#################\r\n");
    g_rpi.printf("#               #\r\n");
    g_rpi.printf("#   I'm alive   #\r\n");
    g_rpi.printf("#               #\r\n");
    g_rpi.printf("#################\r\n");
    g_rpi.printf("\r\n");
```

I don't know why it is set twice, but for sure the nucleo and the rpi can't communicate if they differ in baudrate

**Comment by BFMC-Rares-Lemnariu** [comment]
Hi, 
You can see in the Release notes on the Documentation site ([link](https://bfmcembeddedplatform.readthedocs.io/en/stable/releasenote.html)), we changed the baudrate to 256000 for minimizing the message loss. The new serial handler bases on the same baudrate, you can see in new repository ([link](https://github.com/ECC-BFMC/BFMC2020.Startup/blob/master/src/hardware/serialhandler/serialhandler.py)).
