### ISSUE TITLE
SendMove only works with PWM pulse ( pid activation false)

### ISSUE THREAD

**Issue by dragosmacovei** [ECC-BFMC/Embedded_Platform#2]
`serialHandler.sendBrake(-20.0)` works fine

```
serialHandler.sendPidActivation()
serialHandler.sendMove(0.33,20.0)
```
works fine as well

```
serialHandler.sendPidActivation(False)
serialHandler.sendMove(20.0,20.0)
```
doesn't work anymore.

I also want to mention the fact that the motor still goes crazy if you try to block the wheels or if you touch the encoder's axis.

**Comment by BFMC-Rares-Lemnariu** [comment]
Hi, 
When you run the following block of code: 
`serialHandler.sendPidActivation()
serialHandler.sendMove(0.33,20.0)`

,then you activate the pid and send a 0.33 m/s speed to car. 

When you use the other version of code:
`serialHandler.sendPidActivation(False)
serialHandler.sendMove(20.0,20.0)`

,then the motor speed control is deactivated and you control directly the motor voltage by PWM. In this year version, we change the input parameter for he motor bridge driver. It works with ratio, instead percentage. We mentioned the modification in release note ( [link](https://bfmcembeddedplatform.readthedocs.io/en/stable/releasenote.html)). So the second block of code will be modified like:

`serialHandler.sendPidActivation(False)
serialHandler.sendMove(0.2,20.0)`

I hope I helped you.

**Comment by TudorSante** [comment]
Dead Organizer,

Such advice is of great help.

I've read through the Embedded Platform's doc and I still have some
questions. Regarding the tasks:
Are they intended to be executed at a predefined period? If so(that's what
I understood by reading the doc), what does the run() method stands for?
(Here _run() is overridden to get a particular Task behavior).

Also I want to 'embed' my Grafcet implementation(Attached in the Report#1 -
BackOnTrack) in the whole system. To make use of those tasks(which execute
periodically - as my Grafcet ideally does) - I want to set it as a Task,
map it in the TaskManager(to verify different conditions that trigger
transition => going in other system states) and make it execute at 1 ms
rate(let's say). Is it a good idea? Won't it affect the motor commands that
are also given at 1 ms intervals?

I would truly appreciate a more in-depth doc about these tasks running and
how the callbacks methods work with respect to those.

Thanks in advance!
Tudor S., BackOnTrack Team Leader
