### ISSUE TITLE
Encoder auto return 0

### ISSUE THREAD

**Issue by sonrasa2k** [ECC-BFMC/Embedded_Platform#4]
`self.serialCom = serial.Serial(devFile,19200,timeout=0.1)
 while not rospy.is_shutdown():
 read_chr=self.serialCom.read()`

I turned on the encoder but when the car runs the encoder data still returns 0

**Comment by BFMC-Rares-Lemnariu** [comment]
Is the encoder shaft rotating though?

The encoder returns the speed of the car, not the position. So unless you rotate the motor, it will return 0.

If the car is moving and the shaft as well, then it might be a coding problem. What if you access the nucleo directly from the PC, with putty, and send it the #5:1;; command… it should return the speed as well.

Salutări amicale / Best regards,

Rares Lemnariu

Innovation and University Relations (AE/PJ-IU)
Robert Bosch SRL | Str. Constanta | No. 30-34 | Zip 400158 | Cluj-Napoca | ROMANIA | www.bosch.com.ro
Tel. +40 372 544-376 | ***@***.******@***.***>

Registered Office: Horia Măcelariu 30-34, sector 1, 013937- Bucureşti, Registration Court: J40/ 7601/ 1994
Managing Directors: Director general : Mihai Boldijar, Director economic: Mafteiu Karla

​
From: SON NGUYỄN VĂN ***@***.***>
Sent: Thursday, February 16, 2023 10:37 AM
To: ECC-BFMC/Embedded_Platform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ECC-BFMC/Embedded_Platform] Encoder auto return 0 (Issue #4)


self.serialCom = serial.Serial(devFile,19200,timeout=0.1) while not rospy.is_shutdown(): read_chr=self.serialCom.read()

I turned on the encoder but when the car runs the encoder data still returns 0

**Comment by sonrasa2k** [comment]
> 
although through BFMC/Brain_Ros I have motor working but the return result from encoder is still 0

**Comment by sonrasa2k** [comment]
> Is the encoder shaft rotating though? The encoder returns the speed of the car, not the position. So unless you rotate the motor, it will return 0. If the car is moving and the shaft as well, then it might be a coding problem. What if you access the nucleo directly from the PC, with putty, and send it the #5:1;; command… it should return the speed as well. Salutări amicale / Best regards, Rares Lemnariu Innovation and University Relations (AE/PJ-IU) Robert Bosch SRL | Str. Constanta | No. 30-34 | Zip 400158 | Cluj-Napoca | ROMANIA | [www.bosch.com.ro](http://www.bosch.com.ro) Tel. +40 372 544-376 | ***@***.******@***.***> Registered Office: Horia Măcelariu 30-34, sector 1, 013937- Bucureşti, Registration Court: J40/ 7601/ 1994 Managing Directors: Director general : Mihai Boldijar, Director economic: Mafteiu Karla​From: SON NGUYỄN VĂN ***@***.***> Sent: Thursday, February 16, 2023 10:37 AM To: ECC-BFMC/Embedded_Platform ***@***.***> Cc: Subscribed ***@***.***> Subject: [ECC-BFMC/Embedded_Platform] Encoder auto return 0 (Issue #4) self.serialCom = serial.Serial(devFile,19200,timeout=0.1) while not rospy.is_shutdown(): read_chr=self.serialCom.read() I turned on the encoder but when the car runs the encoder data still returns 0 — Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FECC-BFMC%2FEmbedded_Platform%2Fissues%2F4&data=05%7C01%7Crares.lemnariu%40ro.bosch.com%7C235dca896b99443ee30108db0ff90a4a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638121334525775354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6EAltrmKD3hMrztdChwAQ66YGuymLdNeWc3CDt%2B0aF8%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLYILYHGSV2LQR7LYL7HHTWXXRMRANCNFSM6AAAAAAU53H4JI&data=05%7C01%7Crares.lemnariu%40ro.bosch.com%7C235dca896b99443ee30108db0ff90a4a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638121334525775354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1OW2Xm156wUqRfg0Qt2mhW89EPMX3tRJ9d%2FkV8zl3Hc%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
although through BFMC/Brain_Ros I have motor working but the return result from encoder is still 0

**Comment by BFMC-Rares-Lemnariu** [comment]
The car is keeping it's speed?
Please install putty and connect the nucleo directly tot he PC. Check the COM of the device and then open putty.
Set up putty as follows: 
-Connection type: Serial
-Speed: 19200
-Serial line: COMxx
-Terminal->Local-echo: Force on
-Terminal->Local line editing: Force on

Go to session and press Open

Reset the Nucle (black button). On the terminal you should receive a wake-up message

In terminal, write: 
**#5:1;;** and then press ctrl+m, followed by ctrl+j

Block one wheel and turn the other (same ax). Are the values going up and down?

**Comment by sonrasa2k** [comment]
thank you !

**Comment by sonrasa2k** [comment]
> The car is keeping it's speed? Please install putty and connect the nucleo directly tot he PC. Check the COM of the device and then open putty. Set up putty as follows: -Connection type: Serial -Speed: 19200 -Serial line: COMxx -Terminal->Local-echo: Force on -Terminal->Local line editing: Force on
> 
> Go to session and press Open
> 
> Reset the Nucle (black button). On the terminal you should receive a wake-up message
> 
> In terminal, write: **#5:1;;** and then press ctrl+m, followed by ctrl+j
> 
> Block one wheel and turn the other (same ax). Are the values going up and down?

thank you very much!
